apiVersion: v1
kind: Namespace
metadata:
  name: app-uat
  labels:
    environment: uat
    managed-by: kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-prod
  labels:
    environment: prod
    managed-by: kubernetes

