apiVersion: v1
kind: Namespace
metadata:
  name: app-dev
  labels:
    environment: dev
    managed-by: kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-qat
  labels:
    environment: qat
    managed-by: kubernetes

